import { z } from "zod";
import { AssetType, InputMethod, TapuType, ZoningStatus, RoadAccess, UtilityStatus } from "@parselradar/shared";

export const PropertySubmissionCreateInputSchema = z.object({
  assetType: z.nativeEnum(AssetType),
  inputMethod: z.nativeEnum(InputMethod),
  ilanUrl: z.string().url().optional().or(z.literal("")),
  il: z.string().min(1),
  ilce: z.string().min(1),
  mahalleOrKoy: z.string().min(1),
  addressText: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  askingPriceTRY: z.number().positive().optional(),
  areaM2: z.number().positive().optional(),
  ada: z.string().optional(),
  parsel: z.string().optional(),
  pafta: z.string().optional(),
  nitelik: z.string().optional(),
  tapuType: z.nativeEnum(TapuType),
  zoningStatus: z.nativeEnum(ZoningStatus),
  taks: z.number().optional(),
  kaks: z.number().optional(),
  emsal: z.number().optional(),
  gabari: z.string().optional(),
  hmax: z.string().optional(),
  katAdedi: z.string().optional(),
  cekmeMesafeleri: z.string().optional(),
  planNotlariText: z.string().optional(),
  roadAccess: z.nativeEnum(RoadAccess),
  electricity: z.nativeEnum(UtilityStatus),
  water: z.nativeEnum(UtilityStatus),
  villageDistanceText: z.string().optional(),
  status: z.string().optional(),
});
