// Shared enums for ParselRadar

export enum AssetType {
  ARSA = 'ARSA',
  TARLA = 'TARLA',
  BAHCE = 'BAHCE',
  KONUT = 'KONUT',
  TICARI = 'TICARI',
  PROJE = 'PROJE',
  DIGER = 'DIGER',
}

export enum InputMethod {
  ILAN_URL = 'ILAN_URL',
  SCREENSHOT_UPLOAD = 'SCREENSHOT_UPLOAD',
  ADA_PARSEL = 'ADA_PARSEL',
  MANUAL_ENTRY = 'MANUAL_ENTRY',
}

export enum TapuType {
  MUSTAKIL = 'MUSTAKIL',
  HISSELI = 'HISSELI',
  KAT_IRTIFAKI = 'KAT_IRTIFAKI',
  KAT_MULKIYETI = 'KAT_MULKIYETI',
  UNKNOWN = 'UNKNOWN',
}

export enum ZoningStatus {
  IMARLI = 'IMARLI',
  IMARSIZ = 'IMARSIZ',
  KOY_YERLESIK_ALANI = 'KOY_YERLESIK_ALANI',
  TARIMSAL = 'TARIMSAL',
  BAG_BAHCE = 'BAG_BAHCE',
  TICARI = 'TICARI',
  KONUT = 'KONUT',
  UNKNOWN = 'UNKNOWN',
}

export enum RoadAccess {
  KADASTRO_YOLU = 'KADASTRO_YOLU',
  FIILI_YOL = 'FIILI_YOL',
  YOL_YOK = 'YOL_YOK',
  UNKNOWN = 'UNKNOWN',
}

export enum UtilityStatus {
  VAR = 'VAR',
  YAKIN = 'YAKIN',
  YOK = 'YOK',
  UNKNOWN = 'UNKNOWN',
}

export enum DocumentType {
  ILAN_SCREENSHOT = 'ILAN_SCREENSHOT',
  TAPU_SENEDI = 'TAPU_SENEDI',
  TAPU_KAYIT_BELGESI = 'TAPU_KAYIT_BELGESI',
  TAKYIDAT_BELGESI = 'TAKYIDAT_BELGESI',
  TKGM_PARSEL_SCREENSHOT = 'TKGM_PARSEL_SCREENSHOT',
  ONLINE_IMAR_DURUM_BELGESI = 'ONLINE_IMAR_DURUM_BELGESI',
  BELEDIYE_IMAR_DURUM_BELGESI = 'BELEDIYE_IMAR_DURUM_BELGESI',
  E_IMAR_SCREENSHOT = 'E_IMAR_SCREENSHOT',
  PLAN_NOTLARI = 'PLAN_NOTLARI',
  RUHSAT = 'RUHSAT',
  ISKAN = 'ISKAN',
  KAT_IRTIFAKI_TAPUSU = 'KAT_IRTIFAKI_TAPUSU',
  KAT_MULKIYETI_TAPUSU = 'KAT_MULKIYETI_TAPUSU',
  OTHER = 'OTHER',
}

export enum ProductType {
  QUICK_SCORE = 'QUICK_SCORE',
  PARSEL_INSIGHT = 'PARSEL_INSIGHT',
  DETAILED_PDF_REPORT = 'DETAILED_PDF_REPORT',
  DEVELOPER_FIT = 'DEVELOPER_FIT',
  HUMAN_REVIEW_REQUEST = 'HUMAN_REVIEW_REQUEST',
}

export enum Signal {
  BUY = 'BUY',
  RADAR = 'RADAR',
  WAIT = 'WAIT',
  RISK = 'RISK',
}

export enum CreditLedgerType {
  CREDIT_PURCHASE = 'CREDIT_PURCHASE',
  CREDIT_SPEND = 'CREDIT_SPEND',
  CREDIT_REFUND = 'CREDIT_REFUND',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}

export enum DealPoolStatus {
  NOT_OPTED_IN = 'NOT_OPTED_IN',
  OPTED_IN_PENDING_REVIEW = 'OPTED_IN_PENDING_REVIEW',
  ACCEPTED_TO_DEAL_POOL = 'ACCEPTED_TO_DEAL_POOL',
  REJECTED_RISKY = 'REJECTED_RISKY',
  MATCHING_CANDIDATE = 'MATCHING_CANDIDATE',
  SHARED_WITH_APPROVED_PARTNER = 'SHARED_WITH_APPROVED_PARTNER',
  CLOSED = 'CLOSED',
}

export enum MatchCategory {
  INDIVIDUAL_BUYER = 'INDIVIDUAL_BUYER',
  INVESTOR = 'INVESTOR',
  LICENSED_AGENT = 'LICENSED_AGENT',
  DEVELOPER = 'DEVELOPER',
  CONTRACTOR = 'CONTRACTOR',
  LAND_FOR_UNIT_DEAL = 'LAND_FOR_UNIT_DEAL',
  PORTFOLIO_REVIEW = 'PORTFOLIO_REVIEW',
}
