console.log('=== PILOT CHECKLIST ===');
console.log('\nENV:');
console.log('- All required env vars set and valid (see pilot:env)');
console.log('\nSTRIPE:');
console.log('- Stripe test-mode keys and price IDs configured');
console.log('- Webhook endpoint set and signature verified');
console.log('- Test cards only, no real payments');
console.log('\nMONGODB:');
console.log('- Local or Atlas test DB, no production data');
console.log('- Backup and cleanup procedures ready');
console.log('\nUSER FLOW:');
console.log('- Register/login, buy test credits, submit property, upload Online İmar Durum Belgesi, consent, quick score, purchase PDF, download report, verify preview, admin checks, Deal Pool opt-in');
console.log('\nPDF:');
console.log('- PDF/report generation, watermark, disclaimer, checklist');
console.log('\nSECURITY:');
console.log('- No fullAnalysis exposure, no admin route leaks, ownership checks enforced');
console.log('\nLEGAL:');
console.log('- Terms, privacy, disclaimer shown, explicit Deal Pool opt-in, no hidden data reuse, no investment guarantee');
console.log('\nSTOP CONDITIONS:');
console.log('- Stripe webhook fails, credits mismatch, upload fails, PDF fails, ownership breach, admin route leak, fullAnalysis exposed, smoke fails, missing legal/privacy text');
process.exit(0);
